// show pool
get https://take-me-backend.herokuapp.com/api/driver/pool/

//delete pool
###
get https://take-me-backend.herokuapp.com/api/driver/pool/clean


//owner login
###
post https://take-me-backend.herokuapp.com/api/owner/login
Content-Type: application/json

{
    "email": "bruce@wayne.com",
    "password":  "iAmBatman"
}

//owner dashboard
###
get https://take-me-backend.herokuapp.com/api/owner/dashboard
auth-token: GET_TOKEN_FROM_ADMIN