//variables
@baseUrl = https://take-me-backend.herokuapp.com/api/passenger
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDc0NzgxNzhjMjljMTQwOGNmYWQyOTIiLCJpYXQiOjE2MjQ2NzU4Nzd9.hknL1C0-zQZZFmFaOS2qDdVHiIEYc02BqOu2jUEa19E
//user login
###
post {{baseUrl}}/login
Content-Type: application/json

{
    "email": "ivifo@visinas.st",
    "password":  "WXu25ufe"
}

//search driver
###
post {{baseUrl}}/searchDriver
auth-token: {{token}}
Content-Type: application/json

{
    "requirement": "nearest",
    "pickUpPoint": "[23.784571240,90.34350]",
    "dropOutPoint": "[23.7798586986,90.427278628]"
}

#  90.69696433,
#       23.6995434

//cancel ride
###
post {{baseUrl}}/cancelMatch
auth-token: {{token}}
Content-Type: application/json

{
    "entity": "passenger"
}


//end ride
###
post {{baseUrl}}/endRide
auth-token: {{token}}
Content-Type: application/json

{
    "entity": "passenger",
    "location": "[0.00,0.000]"
}
